stories_flora/main_app/urls.py
from django.urls import path
from . import views
from django.conf.urls import url, include

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    # login
    path('login', views.LoginUser.as_view(), name='login'),
    path('register', views.RegisterUser.as_view(), name='register'),
    path('logout', views.logout_user, name='logout'),
    path('download', views.download_database, name='download_database'),

    # View
    path('', views.StoriesView.as_view(), name='home'),
    path('about', views.AboutView.as_view(), name='about'),
    path('filter', views.FilterStoriesView.as_view(), name='filter'),

    path('story=<int:pk>/', views.StoryDetailView.as_view(), name='story_details'),
    path('story=<int:pk_st>/story_i18n=<int:pk>/', views.Story_i18nDetailView.as_view(), name='story_i18n_details'),

    # Edit
    path('story=<int:pk>/edit', views.StoryEditView.as_view(), name='edit_story'),
    path('story=<int:pk_st>/story_i18n=<int:pk>/edit', views.Story_i18nEditView.as_view(), name='edit_story_i18n'),
    path('story=<int:pk_st>/story_i18n=<int:pk_i18n>/page=<int:pk>-edit', views.PageEditView.as_view(), name='edit_page'),

    # Copy
    path('story=<int:pk>/copy', views.copy_story, name='copy_story'),
    path('story=<int:pk_st>/story_i18n=<int:pk>/copy', views.copy_story_i18n, name='copy_story_i18n'),
    path('story=<int:pk_st>/story_i18n=<int:pk_i18n>/page=<int:pk_page>-copy', views.copy_page, name='copy_page'),

    # Others
    path('languages', views.LanguagesView.as_view(), name='languages'),
    path('categories', views.CategoriesView.as_view(), name='categories'),
    path('category=<int:pk>', views.CategoryDetailView.as_view(), name='category_details'),

    # Add
    path('add-story', views.add_story, name='add_story'),
    path('story=<int:pk_st>/add-story-i18n', views.add_story_i18n, name='add_story_i18n'),
    path('story=<int:pk_st>/story_i18n=<int:pk_i18n>/add-page', views.add_page, name='add_page'),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

stories_flora/stories_flora/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # path('flora-stories-editor/admin/', admin.site.urls),
    # path('flora-stories-editor/', include('main_app.urls')),
    path('admin/', admin.site.urls),  # flora-stories-editor/
    path('', include('main_app.urls')),  # flora-stories-editor/

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

stories_flora/main_app/models.py
from django.conf import settings
from django.db import models
from django.contrib.postgres.fields import ArrayField
import os
import re
from django.core.files.storage import FileSystemStorage
from mdeditor.fields import MDTextField
from urllib.parse import urljoin



class Languages(models.Model):
    language = models.CharField('Language', max_length=30, primary_key=True, unique=True)

    def __str__(self):
        return self.language

    def get_absolute_url(self):
        return f'/languages'

    class Meta:
        verbose_name = 'Language'
        verbose_name_plural = 'Languages'
        db_table = 'languages'


class Categories(models.Model):
    category_priority = models.IntegerField('Category priority', default=50)

    def __str__(self):
        categ_i18n = Categories_i18n.objects.filter(category=self.pk, language="en").first()

        if categ_i18n:
            return "{} - {}".format(self.pk, categ_i18n.name)
        elif self.pk == 1:
            return "{} - {}".format(self.pk, 'News')
        elif self.pk == 2:
            return "{} - {}".format(self.pk, 'Tips')
        else:
            return "{} - {}".format(self.pk, 'category')

    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'
        ordering = ['-pk']
        db_table = 'categories'


class Categories_i18n(models.Model):
    name = models.CharField('Category', default="News", max_length=500)
    language = models.ForeignKey(Languages, verbose_name='Language id', on_delete=models.PROTECT)
    category = models.ForeignKey(Categories, related_name="categoriesi18n_categories", verbose_name='Category id', on_delete=models.PROTECT)

    def __str__(self):
        return "{} - {}".format(self.name, self.language)

    class Meta:
        verbose_name = 'Category_i18n'
        verbose_name_plural = 'Categories_i18n'
        db_table = 'categories_i18n'


class Geolocations(models.Model):
    name = models.CharField('Name', max_length=255)  # null=False is default

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Geolocation'
        verbose_name_plural = 'Geolocations'
        db_table = 'geolocations'


def get_default_clients():
    return None  # this returns a list


def get_default_geolocations():
    return None  # this returns a list
    #return ["Germany", "France"]  # this returns a list


class Stories(models.Model):
    hide_in_stories = models.BooleanField('Hide in stories', default=False)
    post_priority = models.IntegerField('Post priority', default=20)
    fresh_after = models.DateField('Fresh after', null=True, blank=True)  # empty string should be blank=True
    fresh_before = models.DateField('Fresh before', null=True, blank=True)
    clients_eligible = ArrayField(models.IntegerField(), default=get_default_clients,  null=True, blank=True)
    geolocations = ArrayField(models.CharField(max_length=255), default=get_default_geolocations, null=True, blank=True)
    deleted = models.BooleanField('Deleted', default=False)
    category = models.ForeignKey(Categories, related_name="stories_categories", verbose_name='Category id', on_delete=models.PROTECT)

    def save(self, *args, **kwargs):
        if not self.clients_eligible:
            self.clients_eligible = None  # save Null if the field is empty
        if not self.geolocations:
            self.geolocations = None  # save Null if the field is empty
        super().save(*args, **kwargs)

    #  sets what will be output
    def __str__(self):
        return str(self.pk)

    #  forwarding after saving changes(editing)
    def get_absolute_url(self):
        return f'/story={self.pk}'

    # singular, plural variant
    class Meta:
        verbose_name = 'Story'
        verbose_name_plural = 'Stories'
        ordering = ['-pk']  # the first is the newest story
        db_table = 'stories'


def content_file_name_title_icon(instance, filename):
    file_extension = filename.split('.')[-1]
    filename = "title_icon_%s.%s" % (instance, file_extension)
    return os.path.join('stories/title_icon/', filename)


def content_file_name_title_image(instance, filename):
    file_extension = filename.split('.')[-1]
    filename = "title_image_%s.%s" % (instance, file_extension)
    return os.path.join('stories/title_image/', filename)


def content_file_name_icon(instance, filename):
    file_extension = filename.split('.')[-1]
    filename = "icon_%s.%s" % (instance, file_extension)
    return os.path.join('stories/icon/', filename)


def content_file_name_image(instance, filename):
    file_extension = filename.split('.')[-1]
    filename = "image_%s.%s" % (instance, file_extension)
    return os.path.join('stories/image/', filename)

# id_page id_storyi18n id_story 1008 1229 90

class MyOwnStorage(FileSystemStorage):
    def get_available_name(self, name, max_length=None):
        filename, file_extension = os.path.splitext(name)
        if self.exists(name):
            filename = re.sub(r'[0-9]+$',
                         lambda x: f"{str(int(x.group()) + 1).zfill(len(x.group()))}",
                         filename)
            return "%s%s" % (filename, file_extension)
        else:
            return "%s_0%s" % (filename, file_extension)

        # # If the filename already exists, remove it as if it was a true file system
        # if self.exists(name):
        #     os.remove(os.path.join(settings.MEDIA_ROOT, name))


class Stories_i18n(models.Model):
    title = MDTextField('Title')
    subtitle = MDTextField('Subtitle')
    title_icon = models.ImageField(upload_to=content_file_name_title_icon, storage=MyOwnStorage(), verbose_name='Title icon', max_length=500)  # (default)storage=FileSystemStorage()
    title_image = models.ImageField(upload_to=content_file_name_title_image, storage=MyOwnStorage(), verbose_name='Title image', max_length=500)
    language = models.ForeignKey(Languages, verbose_name='Language id', on_delete=models.PROTECT)
    story = models.ForeignKey(Stories, related_name="storiesi18n_stories", verbose_name='Story id', on_delete=models.PROTECT)

    def __str__(self):
        return "{}-{} ({})".format(self.pk, self.language, self.story)

    def get_absolute_url(self):
        return f'/story={self.story}/story_i18n={self.pk}/'

    def save(self, *args, **kwargs):
        # Call the parent save method to save the image
        super().save(*args, **kwargs)

        # Get the URL of the saved image
        media_url = 'http://127.0.0.1:8000/media/'  # http://shafi.tu-ilmenau.de:8000/media/ http://127.0.0.1:8000/media/ http://127.0.0.1:8000/flora-stories-editor/media/

        # http://127.0.0.1:8000/media/stories/title_image/title_image_None-de_107_0.jpg
        url_image = urljoin(media_url, self.title_image.name)
        url_icon = urljoin(media_url, self.title_icon.name)
        print("media_url=", media_url)
        print("self.title_image.name=", self.title_image.name)

        # Update the title_image field to contain the full URL
        self.title_image = url_image
        self.title_icon = url_icon
        super().save(*args, **kwargs)

    class Meta:
        verbose_name = 'Story_i18n'
        verbose_name_plural = 'Stories_i18n'
        db_table = 'stories_i18n'
        ordering = ['-pk']  # the first is the newest


class Pages(models.Model):
    image = models.ImageField(upload_to=content_file_name_image, storage=MyOwnStorage(), verbose_name='Image', max_length=500)
    icon = models.ImageField(upload_to=content_file_name_icon, storage=MyOwnStorage(), verbose_name='Icon', default='assets/icon/icon_startscreen_new.svg', max_length=500)
    headline = MDTextField('Headline')
    text = MDTextField('Text')
    mark_deleted = models.BooleanField('Mark deleted', default=False)
    order = models.IntegerField('Order', default=100)
    story_i18n = models.ForeignKey(Stories_i18n, related_name="pages_storiesi18n", verbose_name='Story_i18n id', on_delete=models.PROTECT)

    def __str__(self):
        return "id:{} story:{}".format(self.pk, self.story_i18n)

    def get_absolute_url(self):
        return f'/story={self.story_i18n.story}/story_i18n={self.story_i18n.pk}/'

    def save(self, *args, **kwargs):
        # Call the parent save method to save the image
        super().save(*args, **kwargs)

        # Get the URL of the saved image
        media_url = 'http://127.0.0.1:8000/media/'  # http://shafi.tu-ilmenau.de:8000/media/ http://127.0.0.1:8000/media/ http://127.0.0.1:8000/flora-stories-editor/media/

        # http://127.0.0.1:8000/media/stories/title_image/title_image_None-de_107_0.jpg
        url_image = urljoin(media_url, self.image.name)
        url_icon = urljoin(media_url, self.icon.name)

        # Update the title_image field to contain the full URL
        self.image = url_image
        self.icon = url_icon
        super().save(*args, **kwargs)

    class Meta:
        verbose_name = 'Page'
        verbose_name_plural = 'Pages'
        db_table = 'pages'
        ordering = ['order']  # in ascending order
        unique_together = ('story_i18n', 'order',)

stories_flora/main_app/forms.py
from .models import Stories, Stories_i18n, Pages, Languages, Categories, Categories_i18n
from django.forms import ModelForm, TextInput, Textarea, DateInput, Select, NumberInput, ImageField, forms, EmailInput, \
    PasswordInput
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User



class StoriesForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['category'].empty_label = "Select..."

    class Meta:
        model = Stories  # table
        # fields = ['id', 'category', 'hide_in_stories', 'post_priority', 'fresh_after', 'fresh_before',
        #           'geolocations', 'clients_eligible', 'deleted']  # столбцы fields = '__all__'
        fields = '__all__'
        # characteristics for each column
        widgets = {
            "category": Select(attrs={
                'class': 'form-control',
                'placeholder': 'Category id'
            }),
            "post_priority": NumberInput(attrs={
                'class': 'form-control',
                'placeholder': 'Fresh before date'
            }),
            "fresh_after": DateInput(attrs={
                'class': 'form-control',
                'type': "date",
                'placeholder': 'dd-mm-yyyy'
            }),
            "fresh_before": DateInput(attrs={
                'class': 'form-control',
                'type': "date",
                'placeholder': 'Fresh before date'
            }),
            "geolocations": TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Geolocations'
            }),

            "clients_eligible": TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Clients eligible'
            })
        }


class Stories_i18nForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['story'].empty_label = "Select..."
        self.fields['language'].empty_label = "Select..."

    class Meta:
        model = Stories_i18n
        fields = ['story', 'language', 'title_icon', 'title_image', 'title', 'subtitle']
        widgets = {
            "story": Select(attrs={
                'class': 'form-control',
                'placeholder': 'Story id'
            }),
            "language": Select(attrs={
                'class': 'form-control',
                'placeholder': 'Language id'
            }),
            "title": Textarea(attrs={
                'class': 'form-control',

                'placeholder': 'Title'
            }),
            "subtitle": Textarea(attrs={
                'class': 'form-control',
                'rows': 4,
                'placeholder': 'Subtitle'
            })
            # "title_icon": ImageField(attrs={
            #     'class': 'form-control'
            #
            # }),
            # "title_image": ImageField(attrs={
            #     'class': 'form-control'
            #
            # })
        }


class PagesForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['story_i18n'].empty_label = "Select..."

    class Meta:
        model = Pages
        fields = ['story_i18n', 'mark_deleted', 'order', 'image', 'icon', 'headline', 'text']
        widgets = {
            "story_i18n": Select(attrs={
                'class': 'form-control',
                'placeholder': 'Story_i18n id'
            }),
            # "image": ImageField(attrs={
            #     'class': 'form-control',
            #     'placeholder': 'Image'
            # }),
            # "icon": ImageField(attrs={
            #     'class': 'form-control',
            #     'placeholder': 'Icon'
            # }),
            "headline": Textarea(attrs={
                'class': 'form-control',
                'rows': 6,
                'placeholder': 'Headline'
            }),
            "text": Textarea(attrs={
                'class': 'form-control',
                'rows': 16,
                'placeholder': 'Text'
            }),
            "order": NumberInput(attrs={
                'class': 'form-control',
                'placeholder': 'Order'
            }),
        }


class RegisterUserForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super(RegisterUserForm, self).__init__(*args, **kwargs)
        self.fields['password1'].widget = PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Password'})
        self.fields['password2'].widget = PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Repeat password'})

    class Meta:
        model = User  # table(model) auth_user
        fields = ('username', 'email', 'password1', 'password2')
        widgets = {
            "username": TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Username'
            }),
            "email": EmailInput(attrs={
                'class': 'form-control',
                'placeholder': 'Email'
            })
        }


class LoginUserForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super(LoginUserForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget = TextInput(attrs={'class': 'form-control', 'placeholder': 'Username'})
        self.fields['password'].widget = PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Password'})


# class LanguagesForm(ModelForm):
#     class Meta:
#         model = Languages  # table
#        # fields = '__all__'  # 'language'
#         fields = ['language']
#         widgets = {
#             "language": TextInput(attrs={
#                 'class': 'form-control',
#                 'placeholder': 'Language'
#             })
#         }
#

stories_flora/main_app/templates/main_app/about.html
{% extends 'main_app/layout.html' %}

{% block title %} About {% endblock %}

{% block content %}
       <div class="features">
           <h1>About us</h1>
           <p class="p_temp">What is it that blooms so beautifully on the side of the road? If you want to identify wild plants with confidence, it is best to download the application "Flora Incognita", which we offer to download here for Android.</p>

       </div>
{% endblock %}

stories_flora/main_app/templates/main_app/add_page.html
{% extends 'main_app/layout.html' %}

{% block title %} Create page for story {% endblock %}

{% block content %}
<div class="features">
    <h1>Create page</h1>
    <div class="tank-forms">
         <div class="head-polaroid page">

              <form action="{% url 'add_page' pk_st=1 pk_i18n=1 %}" method="post" enctype="multipart/form-data">
                  {% csrf_token %}
                  {{ form_page.media }}
<!--                  {% for form in form_page %}-->
<!--                      <p><label class="title-label-page" for="{{ form.id_for_label }}">{{form.label}}: </label>{{ form }}</p>-->
<!--                      <div class="form-error">{{ form.errors }}</div>-->
<!--                  {% endfor %}-->
                  <p><label class="title-label-page" for="{{ form_page.story_i18n.id_for_label }}">{{form_page.story_i18n.label}}: </label>{{ form_page.story_i18n }}</p>
                  <div class="form-error">{{ form_page.story_i18n.errors }}</div>
                  <p><label class="title-label-page" for="{{ form_page.mark_deleted.id_for_label }}">{{form_page.mark_deleted.label}}: </label>{{ form_page.mark_deleted }}</p>
                  <div class="form-error">{{ form_page.mark_deleted.errors }}</div>

<!--              <p><label class="title-label-story" for="{{ form_story.order.id_for_label }}">{{form_story.order.label}}: </label>{{ form_story.order }}</p>-->
                  <p>
                      <label class="title-label-page" for="id_order">Order: </label>
                      <input type="number" name="order" value={{ max_order }} class="form-control" placeholder="Order" required id="id_order">
                  </p>
                  <div class="form-error">{{ form_story.order.errors }}</div>
                  <div class="form-error">{{ error_message }}</div>

                  <p><label class="title-label-page" for="{{ form_page.image.id_for_label }}">{{form_page.image.label}}: </label>{{ form_page.image }}</p>
                  <div class="form-error">{{ form_page.image.errors }}</div>
                  <p><label class="title-label-page" for="{{ form_page.icon.id_for_label }}">{{form_page.icon.label}}: </label>{{ form_page.icon }}</p>
                  <div class="form-error">{{ form_page.icon.errors }}</div>
                  <p><label class="title-label-page" for="{{ form_page.headline.id_for_label }}">{{form_page.headline.label}}: </label>{{ form_page.headline }}</p>
                  <div class="form-error">{{ form_page.headline.errors }}</div>
                  <p><label class="title-label-page" for="{{ form_page.text.id_for_label }}">{{form_page.text.label}}: </label>{{ form_page.text }}</p>
                  <div class="form-error">{{ form_page.text.errors }}</div>


                 <div class="div-bt">
                     <button class="button button_save" type="submit"><i class="fas fa-plus-circle" style="font-size: 1.2rem; color: #183153;"></i> Add</button>
                     <a class="button button_del" onClick="javascript:history.go(-1);"><i class="fa-solid fa-rectangle-xmark" style="font-size: 1.25rem; color: #183153;"></i> Cancel</a>
                 </div>
             </form>
         </div>
    </div>

</div>
{% endblock %}

stories_flora/main_app/templates/main_app/add_story.html
{% extends 'main_app/layout.html' %}

{% block title %} Create story {% endblock %}

{% block content %}
<div class="features">
    <h1>Create story</h1>
    <div class="tank-forms-story">
         <div class="head-polaroid">
            <form action="{% url 'add_story' %}" method="post">
                {% csrf_token %}

                <p><label class="title-label-story" for="{{ form_story.category.id_for_label }}">{{form_story.category.label}}: </label>{{ form_story.category }}</p>
                <div class="form-error">{{ form_story.category.errors }}</div>
                <p><label class="title-label-story" for="{{ form_story.hide_in_stories.id_for_label }}">{{form_story.hide_in_stories.label}}: </label>{{ form_story.hide_in_stories }}</p>
                <div class="form-error">{{ form_story.hide_in_stories.errors }}</div>
                <p><label class="title-label-story" for="{{ form_story.deleted.id_for_label }}">{{form_story.deleted.label}}: </label>{{ form_story.deleted }}</p>
                <div class="form-error">{{ form_story.deleted.errors }}</div>
                <p><label class="title-label-story" for="{{ form_story.post_priority.id_for_label }}">{{form_story.post_priority.label}}: </label>{{ form_story.post_priority }}</p>
                <div class="form-error">{{ form_story.post_priority.errors }}</div>
                <p><label class="title-label-story" for="{{ form_story.fresh_after.id_for_label }}">{{form_story.fresh_after.label}}: </label>{{ form_story.fresh_after }}</p>
                <div class="form-error">{{ form_story.fresh_after.errors }}</div>
                <p><label class="title-label-story" for="{{ form_story.fresh_before.id_for_label }}">{{form_story.fresh_before.label}}: </label>{{ form_story.fresh_before }}</p>
                <div class="form-error">{{ form_story.fresh_before.errors }}</div>
                <p><label class="title-label-story" for="{{ form_story.clients_eligible.id_for_label }}">{{form_story.clients_eligible.label}}: </label>{{ form_story.clients_eligible }}</p>
                <div class="form-error">{{ form_story.clients_eligible.errors }}</div>



                <p ><label class="title-label-story" for="{{ form_story.geolocations.id_for_label }}">{{form_story.geolocations.label}}: </label>{{ form_story.geolocations }}</p>
<!--                hidden <p>-->
<!--                    <label class="title-label-story" for="id_geolocations">Geolocations: </label>-->
<!--	                <input type="text" name="geolocations" value="Germany,France" class="form-control" placeholder="Geolocations" required="" id="id_geolocations">-->
<!--	                <input type="hidden" name="initial-geolocations"  id="initial-id_geolocations">-->
<!--                </p>-->
                <label class="title-label-story" for="id_geolocations">Geolocations static list: </label>
                <div class="form-error">{{ form_story.geolocations.errors }}</div>

                <!-- items from table Geolocations-->
                <select id="select-geo" multiple style="width: 100%; padding: 0.375rem 0.75rem;">
                    {% for geo in geo_values %}
                        <option value="{{ geo.pk }}" >{{ geo.name }}</option>
                    {% endfor %}
                </select>



                <div class="div-bt">
                    <button class="button button_save" type="submit"><i class="fas fa-plus-circle" style="font-size: 1.2rem; color: #183153;"></i> Add</button>
                    <a href="{% url 'home' %}" class="button button_del"><i class="fa-solid fa-rectangle-xmark" style="font-size: 1.25rem; color: #183153;"></i>  Cancel</a>
                </div>
            </form>
         </div>
    </div>

</div>
{% endblock %}

stories_flora/main_app/templates/main_app/add_story_i18n.html
{% extends 'main_app/layout.html' %}

{% block title %} Create language of story {% endblock %}

{% block content %}
<div class="features">
    <h1>Create translation story</h1>
    <div class="tank-forms">
         <div class="head-polaroid static_i18n">
             <form action="{% url 'add_story_i18n' pk_st=1 %}" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form_story_i18n.media }}
                {% for form in form_story_i18n %}
                    <p><label class="title-label-i18n" for="{{ form.id_for_label }}">{{form.label}}: </label>{{ form }}</p>
                    <div class="form-error">{{ form.errors }}</div>
                {% endfor %}

                 <div class="div-bt">
                     <button class="button button_save" type="submit"><i class="fas fa-plus-circle" style="font-size: 1.2rem; color: #183153;"></i> Add</button>
                     <a href="{% url 'story_details' form_story_i18n.story.value %}" class="button button_del"><i class="fa-solid fa-rectangle-xmark" style="font-size: 1.25rem; color: #183153;"></i>  Cancel</a>
                 </div>
             </form>
         </div>
    </div>

</div>
{% endblock %}

stories_flora/main_app/templates/main_app/categories.html
{% extends 'main_app/layout.html' %}

{% block title %} Categories {% endblock %}

{% block content %}
<div class="features">
    <h1>Categories ({{ categories.count }}):</h1>
    <div class="grid-categ">
        {% if categories %}
        {% for categ in categories %}
        <div class="polaroid polaroid-categ">
            <div class="container">
                <div class="item-center-bold story-title">Id:</div>
                <div class="item-center-normal story-text">{{ categ.pk }}</div>
                <div class="item-center-bold story-title">Category priority:</div>
                <div class="item-center-normal story-text">{{ categ.category_priority }}</div>

                 <div class="grid-two-columns item-center-normal">
                    <a href="{% url 'category_details' categ.pk %}" class="button button_read">Details <i class="fa-solid fa-right-to-bracket" style="font-size: 1.1rem; color: #183153;"></i></a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
    {% else %}
    <p>There is no category</p>
    {% endif %}
</div>
{% endblock %}

stories_flora/main_app/templates/main_app/edit_page.html
{% extends 'main_app/layout.html' %}

{% block title %} Edit page {% endblock %}

{% block content %}
<div class="features">
    <h1>Edit page</h1>
     <div class="tank-forms">
         <div class="head-polaroid page">
             <form method="post" enctype="multipart/form-data">
                 {% csrf_token %}
                 {{ form_page.media }}
                 <p><label class="title-label-page">Page id: {{ form_page.instance.id }}</label></p>
                 {% for form in form_page %}
                     <p><label class="title-label-page" for="{{ form.id_for_label }}">{{form.label}}: </label>{{ form }}</p>
                     <div class="form-error">{{ form.errors }}</div>
                 {% endfor %}
                 <div class="form-error">{{ error_message }}</div>
                 <div class="div-bt">
                     <button class="button button_save" type="submit"><i class="fa-solid fa-floppy-disk" style="font-size: 1.2rem; color: #183153;"></i> Save</button>
                     <a class="button button_del" onClick="javascript:history.go(-1);"><i class="fa-solid fa-rectangle-xmark" style="font-size: 1.25rem; color: #183153;"></i> Cancel</a>
                 </div>
             </form>
         </div>
    </div>

</div>
{% endblock %}

stories_flora/main_app/templates/main_app/edit_story_i18n.html
{% extends 'main_app/layout.html' %}

{% block title %} Edit translation story {% endblock %}

{% block content %}
<div class="features">
    <h1>Edit translation story</h1>
     <div class="tank-forms">
         <div class="head-polaroid static_i18n">
             <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form_story_i18n.media }}
                <p><label class="title-label-i18n">Story translation id: {{ form_story_i18n.instance.id }}</label></p>
                {% for form in form_story_i18n %}
                    <p><label class="title-label-i18n" for="{{ form.id_for_label }}">{{form.label}}: </label>{{ form }}</p>
                    <div class="form-error">{{ form.errors }}</div>
                {% endfor %}
                 <div class="div-bt">
                     <button class="button button_save" type="submit"><i class="fa-solid fa-floppy-disk" style="font-size: 1.2rem; color: #183153;"></i> Save</button>
                     <a class="button button_del" onClick="javascript:history.go(-1);"><i class="fa-solid fa-rectangle-xmark" style="font-size: 1.25rem; color: #183153;"></i> Cancel</a>
                 </div>
             </form>
         </div>
    </div>

</div>
{% endblock %}

stories_flora/main_app/templates/main_app/languages.html
{% extends 'main_app/layout.html' %}

{% block title %} Languages {% endblock %}

{% block content %}
<div class="features">
    <h1>Languages ({{ languages.count }}):</h1>
        <div class="grid-lang">
            {% if languages %}
            {% for lan in languages %}
                <div class="polaroid polaroid-lang">
                    <div class="container">
                        <div class="item-center-bold story-title">Id:</div>
                        <div class="item-center-normal story-text">{{ lan.pk }}</div>
                    </div>
                </div>
            {% endfor %}
            {% else %}
                <p>There is no language</p>
            {% endif %}
        </div>
</div>
{% endblock %}